import url from 'utils/routes';

const SERVER_URLS = {
  SIGN_IN: url('/api/v1/users/sign-in/'),
  SIGN_IN_VERIFY: url('/api/v1/users/sign-in-verify'),
  SIGN_OUT: url('/api/v1/users/sign-out/'),
  SIGN_UP_STEP_1: url('/api/v1/users/sign-up/'),
  SIGN_UP_STEP_2: url('/api/v1/users/sign-up/step2/:userPk/'),
  RESET_PASSWORD_STEP_1: url('/api/v1/users/reset-password/'),
  RESET_PASSWORD_STEP_2: url('/api/v1/users/reset-password/step2/:userPk/'),
  SELECTS: {
    COUNTRY: url('/api/v1/selects/country/'),
    REGION: url('/api/v1/selects/region/'),
    CITY: url('/api/v1/selects/city/'),
    CHAT_MODERATORS: url('/api/v1/selects/chat/moderators/'),
    CHAT_USERS: url('/api/v1/selects/chat/users/'),
    MODERATORS: url('/api/v1/selects/moderators/'),
    CLUBS: url('/api/v1/selects/clubs/'),
  },
  IMAGE_EDITOR_UPLOAD: url('/api/v1/storage/images/upload/'),
  IMAGE_UPLOAD: url('/api/v1/storage/images/create/'),
  IMAGE_DELETE: url('/api/v1/storage/images/delete/:imagePk/'),
  FILE_UPLOAD: url('/api/v1/storage/files/create/'),
  FILE_DELETE: url('/api/v1/storage/files/delete/:filePk/'),
  PROFILE: url('/api/v1/users/profile/:userSlug/'),
  PROFILE_PK: url('/api/v1/users/profile/pk/:userPk/'),
  PROFILE_UPDATE: url('/api/v1/users/profile/:userSlug/update/'),
  PROFILE_PASSWORD: url('/api/v1/users/profile/:userSlug/password/'),
  PROFILE_DELETE: url('/api/v1/users/profile/:userSlug/delete/'),
  PROFILE_GIVE_REAL_STATUS: url(
    '/api/v1/users/profile/:userSlug/give_real_status/',
  ),
  FRIENDS_SEARCH: url('/api/v1/users/friends/search/'),
  FRIENDS_LIST: url('/api/v1/users/friends/list/'),
  FRIENDS_DELETE: url('/api/v1/users/friends/delete/:userSlug/'),
  PARTICIPANTS_LIST: url('/api/v1/users/participants/list/'),
  BLACKLIST_LIST: url('/api/v1/users/blacklist/list/'),
  BLACKLIST_CREATE: url('/api/v1/users/blacklist/create/'),
  BLACKLIST_DELETE: url('/api/v1/users/blacklist/delete/:blacklistPk/'),
  MEMBERSHIP_REQUESTS_LIST: url('/api/v1/memberships/list/'),
  MEMBERSHIP_REQUESTS_CREATE: url('/api/v1/memberships/create/'),
  MEMBERSHIP_REQUESTS_UPDATE: url('/api/v1/memberships/update/:membershipPk/'),
  MEMBERSHIP_REQUESTS_DELETE: url('/api/v1/memberships/delete/:membershipPk/'),
  POSTS: url('/api/v1/posts/'),
  POSTS_DETAIL_PK: url('/api/v1/posts/pk/:postPk/'),
  POSTS_DETAIL: url('/api/v1/posts/:postSlug/'),
  POSTS_CREATE: url('/api/v1/posts/create/'),
  POSTS_UPDATE: url('/api/v1/posts/:postSlug/update/'),
  POSTS_DELETE: url('/api/v1/posts/:postSlug/delete/'),
  POSTS_LIKE: url('/api/v1/posts/:postSlug/like/'),
  WHISPER_TO_MODERATE: url('/api/v1/posts/:postSlug/whisper-to-moderate/'),
  POSTS_TO_MODERATE: url('/api/v1/posts/:postSlug/post-to-moderate/'),
  COMMENT_LIST: url('/api/v1/comments/list/'),
  COMMENT_CREATE: url('/api/v1/comments/create/'),
  COMMENT_UPDATE: url('/api/v1/comments/:commentPk/update/'),
  COMMENT_DELETE: url('/api/v1/comments/:commentPk/delete/'),
  COMMENT_LIKE: url('/api/v1/comments/:commentPk/like/'),
  NEWS_LIST: url('/api/v1/news/'),
  NEWS_DETAIL: url('/api/v1/news/:newsPk/'),
  NEWS_LIKE: url('/api/v1/news/:newsPk/like/'),
  MEDIA_FOLDER: url('/api/v1/media/folder/'),
  MEDIA_FOLDER_DETAIL: url('/api/v1/media/folder/:mediaFolderPk/'),
  MEDIA_FOLDER_CREATE: url('/api/v1/media/folder/create/'),
  MEDIA_FOLDER_UPDATE: url('/api/v1/media/folder/:mediaFolderPk/update/'),
  MEDIA_FOLDER_DELETE: url('/api/v1/media/folder/:mediaFolderPk/delete/'),
  MEDIA: url('/api/v1/media/media/'),
  MEDIA_DETAIL: url('/api/v1/media/media/:mediaPk/'),
  MEDIA_CREATE: url('/api/v1/media/media/create/'),
  MEDIA_UPDATE: url('/api/v1/media/media/:mediaPk/update/'),
  MEDIA_DELETE: url('/api/v1/media/media/:mediaPk/delete/'),
  MEDIA_LIKE: url('/api/v1/media/media/:mediaPk/like/'),
  MEDIA_TO_MODERATE_MEDIA_SECTION: url(
    '/api/v1/media/media/:mediaPk/to-moderate-media/',
  ),
  MEDIA_TO_MODERATE_HOT_SECTION: url(
    '/api/v1/media/media/:mediaPk/to-moderate-hot/',
  ),
  CHAT_LIST: url('/api/v1/chats/list/'),
  CHAT_DETAIL: url('/api/v1/chats/:chatPk/detail/'),
  CHAT_CONVERSATION_CREATE: url('/api/v1/chats/conversation/create/'),
  CHAT_CREATE: url('/api/v1/chats/chat/create/'),
  CHAT_WITH_MODERATORS_CREATE: url(
    '/api/v1/chats/chat_with_moderators/create/',
  ),
  CHAT_WITH_DEVELOPERS_CREATE: url(
    '/api/v1/chats/chat_with_developers/create/',
  ),
  CHAT_WITH_MODERATORS_CHECK: url('/api/v1/chats/chat_with_moderators/check/'),
  CHAT_WITH_DEVELOPERS_CHECK: url('/api/v1/chats/chat_with_developers/check/'),
  CHAT_UPDATE: url('/api/v1/chats/:chatPk/update/'),
  CHAT_DELETE: url('/api/v1/chats/:chatPk/delete/'),
  CHAT_LEAVE: url('/api/v1/chats/:chatPk/leave/'),
  CHAT_BAN: url('/api/v1/chats/:chatPk/ban/user/'),
  CHAT_BLOCK: url('/api/v1/chats/:chatPk/block/user/'),
  CHAT_DETAIL_READ_ALL: url('/api/v1/chats/:chatPk/read-all/'),
  CHAT_READ_ALL: url('/api/v1/chats/read-all/'),
  MESSAGE_LIST: url('/api/v1/chats/message/list/'),
  MESSAGE_CREATE: url('/api/v1/chats/message/create/'),
  MESSAGE_UPDATE: url('/api/v1/chats/message/:messagePk/update/'),
  MESSAGE_DELETE: url('/api/v1/chats/message/:messagePk/delete/'),
  GROUP_LIST: url('/api/v1/groups/'),
  GROUP_DETAIL: url('/api/v1/groups/:groupSlug/detail/'),
  GROUP_CREATE: url('/api/v1/groups/create/'),
  GROUP_UPDATE: url('/api/v1/groups/:groupSlug/update/'),
  GROUP_DELETE: url('/api/v1/groups/:groupSlug/delete/'),
  GROUP_LEAVE: url('/api/v1/groups/:groupSlug/leave/'),
  CLUB_LIST: url('/api/v1/clubs/'),
  CLUB_DETAIL: url('/api/v1/clubs/:clubSlug/detail/'),
  CLUB_CREATE: url('/api/v1/clubs/create/'),
  CLUB_UPDATE: url('/api/v1/clubs/:clubSlug/update/'),
  CLUB_DELETE: url('/api/v1/clubs/:clubSlug/delete/'),
  CLUB_LEAVE: url('/api/v1/clubs/:clubSlug/leave/'),
  PARTY_LIST: url('/api/v1/events/'),
  PARTY_DETAIL: url('/api/v1/events/:partySlug/detail/'),
  PARTY_CREATE: url('/api/v1/events/create/'),
  PARTY_UPDATE: url('/api/v1/events/:partySlug/update/'),
  PARTY_DELETE: url('/api/v1/events/:partySlug/delete/'),
  PARTY_LIKE: url('/api/v1/events/:partySlug/like/'),
  PARTY_APPLY: url('/api/v1/events/:partySlug/apply/'),
  GAME_LIST: url('/api/v1/games/'),
  GAME_DETAIL: url('/api/v1/games/retrieve/:gameSlug/'),
  GAME_UPDATE: url('/api/v1/games/update/:gameSlug/'),
  GAME_DELETE: url('/api/v1/games/delete/:gameSlug/'),
  GAME_USER_DETAIL: url('/api/v1/games/user/retrieve/:gameUserPk/'),
  GAME_USER_CREATE: url('/api/v1/games/user/create/'),
  GAME_USER_UPDATE: url('/api/v1/games/user/update/:gameUserPk/'),
  GAME_USER_DELETE: url('/api/v1/games/user/delete/:gameUserPk/'),

  MODERATION_CHAT_WITH_MODERATORS_AND_DEVELOPERS_LIST: url(
    '/api/v1/moderation/chat_with_moderators_and_developers/',
  ),
  MODERATION_USERS: url('/api/v1/moderation/users/'),
  MODERATION_USER_TOGGLE_BAN: url(
    '/api/v1/moderation/users/:userPk/toggle/ban/',
  ),
  MODERATION_USER_SET_MEMBER: url(
    '/api/v1/moderation/users/:userPk/set/member/',
  ),
  MODERATION_USER_SET_REAL: url('/api/v1/moderation/users/:userPk/set/real/'),
  MODERATION_CLUBS: url('/api/v1/moderation/clubs/'),
  MODERATION_CLUB_TOGGLE_BAN: url(
    '/api/v1/moderation/clubs/:clubPk/toggle/ban/',
  ),
  MODERATION_CLUB_APPROVE: url('/api/v1/moderation/clubs/:clubPk/approve/'),
  MODERATION_CLUB_DECLINE: url('/api/v1/moderation/clubs/:clubPk/decline/'),
  MODERATION_PARTIES: url('/api/v1/moderation/parties/'),
  MODERATION_PARTY_TOGGLE_BAN: url(
    '/api/v1/moderation/parties/:partyPk/toggle/ban/',
  ),
  MODERATION_PARTY_APPROVE: url('/api/v1/moderation/parties/:partyPk/approve/'),
  MODERATION_PARTY_DECLINE: url('/api/v1/moderation/parties/:partyPk/decline/'),
  MODERATION_MEDIA: url('/api/v1/moderation/media/'),
  MODERATION_MEDIA_TOGGLE_BAN: url(
    '/api/v1/moderation/media/:mediaPk/toggle/ban/',
  ),
  MODERATION_MEDIA_APPROVE: url('/api/v1/moderation/media/:mediaPk/approve/'),
  MODERATION_MEDIA_DECLINE: url('/api/v1/moderation/media/:mediaPk/decline/'),
  MODERATION_POSTS: url('/api/v1/moderation/posts/'),
  MODERATION_POST_TOGGLE_BAN: url(
    '/api/v1/moderation/posts/:postPk/toggle/ban/',
  ),
  MODERATION_POST_APPROVE: url('/api/v1/moderation/posts/:postPk/approve/'),
  MODERATION_POST_DECLINE: url('/api/v1/moderation/posts/:postPk/decline/'),
  MODERATION_NEWS_LIST: url('/api/v1/moderation/news/'),
  MODERATION_NEWS_DETAIL: url('/api/v1/moderation/news/detail/:newsPk/'),
  MODERATION_NEWS_CREATE: url('/api/v1/moderation/news/create/'),
  MODERATION_NEWS_UPDATE: url('/api/v1/moderation/news/update/:newsPk/'),
  MODERATION_NEWS_DELETE: url('/api/v1/moderation/news/delete/:newsPk/'),

  SOCKJS: url('/sockjs/:userPk/'),
  COUNTERS: url('/api/v1/notifications/counters/'),
  MAP: url('/api/v1/events/map/'),
  CALENDAR: url('/api/v1/events/calendar/'),

  MOBILE_VERSION: url('/api/v1/mobile/version/'),
};

export default SERVER_URLS;
