export const PERMISSION_DENIED = 'PERMISSION_DENIED';
export const ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND';
export const MAINTENANCE = 'MAINTENANCE';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
